/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.clientes.view;

import br.com.clientes.control.CaixaDAO;
import br.com.clientes.modelo.Caixa;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author geova
 */
public class Cadastro extends javax.swing.JFrame {
    CaixaDAO controle = new CaixaDAO();
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        txtPainel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registro = new javax.swing.JLabel();
        txtReg = new javax.swing.JTextField();
        descricao = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        tipo1 = new javax.swing.JLabel();
        valor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnGravar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnSaida = new javax.swing.JRadioButton();
        btnEntrada = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPainel = new javax.swing.JTextArea();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        bgcad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        registro.setForeground(new java.awt.Color(255, 255, 255));
        registro.setText("Registro:");
        getContentPane().add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 30));

        txtReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegActionPerformed(evt);
            }
        });
        getContentPane().add(txtReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 410, -1));

        descricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descricao.setForeground(new java.awt.Color(255, 255, 255));
        descricao.setText("Descrição:");
        getContentPane().add(descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, 30));

        txtDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescActionPerformed(evt);
            }
        });
        getContentPane().add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 500, -1));

        tipo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipo1.setForeground(new java.awt.Color(255, 255, 255));
        tipo1.setText("Tipo:");
        getContentPane().add(tipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 50, 30));

        valor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valor.setForeground(new java.awt.Color(255, 255, 255));
        valor.setText("Valor:");
        getContentPane().add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 50, 30));

        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 200, -1));

        btnGravar.setText("GRAVAR");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, -1));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));

        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        getContentPane().add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        btnSaida.setForeground(new java.awt.Color(255, 255, 255));
        btnSaida.setText("Saida");
        getContentPane().add(btnSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        btnEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrada.setText("Entrada");
        getContentPane().add(btnEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txtPainel.setColumns(20);
        txtPainel.setRows(5);
        jScrollPane3.setViewportView(txtPainel);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 500, 130));

        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        bgcad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clientes/view/ori.png"))); // NOI18N
        getContentPane().add(bgcad, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 550, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        setVisible(false); 
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        int c = Integer.parseInt(txtReg.getText());
        Caixa cx = controle.buscar(c);
        if (cx!=null){
            txtPainel.setText("Resultados encontrados com sucesso!");
            txtReg.setText(""+cx.getRegistro());
            txtDesc.setText(cx.getDescricao());
            if(cx.getTipo()=='E'){
            txtValor.setText(Float.toString(cx.getValor()));
            btnEntrada.setSelected(true);
            btnSaida.setSelected(false);
            } else {
              txtValor.setText(Float.toString(cx.getValor()*(-1)));
              btnSaida.setSelected(true);
              btnEntrada.setSelected(false);
            }
        } else {
            txtPainel.setText("Nenhum dado encontrado!");
            txtDesc.setText("");
            txtValor.setText("");
            btnEntrada.setSelected(false);
            btnSaida.setSelected(false);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        if (Integer.parseInt(txtValor.getText())<0)
        {
            JOptionPane.showMessageDialog(null, "DIGITE VALORES MAIORES QUE "
                + "ZERO, MESMO SE FOR VALORES DE SAÍDA!","ERRO", JOptionPane.ERROR_MESSAGE);
        }else if (btnEntrada.isSelected() && btnSaida.isSelected()){
            JOptionPane.showMessageDialog(null, "Selecione apenas uma opção !","ERRO", JOptionPane.ERROR_MESSAGE);
        } else {        
        Caixa cx = new Caixa();
        int     r = Integer.parseInt(txtReg.getText());
        String  d = txtDesc.getText();
        char  t;
        float v;
        if (btnEntrada.isSelected()){
        v = Float.parseFloat(txtValor.getText());
        t = 'E'; 
        } else {
        v = Float.parseFloat(txtValor.getText()) * (-1);
        t = 'S';
        }
        cx.setRegistro(r); 
        cx.setDescricao(d);
        cx.setValor(v);
        cx.setTipo(t);
        if (controle.incluir(cx))
            JOptionPane.showMessageDialog(null,
                    "Dados Gravados com Sucesso");
        else
            JOptionPane.showMessageDialog(null,
                    "Erro na Gravação dos Dados");
            txtReg.setText("");
            txtDesc.setText("");
            txtValor.setText("");
            btnEntrada.setSelected(false);
            btnSaida.setSelected(false);
        }
        
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        txtPainel.setVisible(true);
        txtPainel.setText("");
        txtPainel.setText(listagem(controle));
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        Caixa cx = new Caixa();
        int r = Integer.parseInt(txtReg.getText());
        String d = txtDesc.getText();
        char  t;
        float v;
        if (btnEntrada.isSelected()){
        v = Float.parseFloat(txtValor.getText());
        t = 'E'; 
        } else {
        v = Float.parseFloat(txtValor.getText()) * (-1);
        t = 'S';
        }
        cx.setRegistro(r); 
        cx.setDescricao(d);
        cx.setValor(v);
        cx.setTipo(t);
        if (controle.alterar(cx))
            txtPainel.setText("Dados Alterados com Sucesso");
        else
            txtPainel.setText("Erro em alterar os Dados");
            txtReg.setText("");
            txtDesc.setText("");
            txtValor.setText("");
            btnEntrada.setSelected(false);
            btnSaida.setSelected(false);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Caixa cx = new Caixa();
        int r = Integer.parseInt(txtReg.getText());
        String d = txtDesc.getText();
        char  t;
        float v;
        if (btnEntrada.isSelected()){
        v = Float.parseFloat(txtValor.getText());
        t = 'E'; 
        } else {
        v = Float.parseFloat(txtValor.getText()) * (-1);
        t = 'S';
        }
        cx.setRegistro(r); 
        cx.setDescricao(d);
        cx.setValor(v);
        cx.setTipo(t);
        if (controle.deletar(cx))
            txtPainel.setText("Dados Excluidos com Sucesso");
        else{
            txtPainel.setText("Erro em excluir os Dados");}
            txtReg.setText("");
            txtDesc.setText("");
            txtValor.setText("");
            btnEntrada.setSelected(false);
            btnSaida.setSelected(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }
    
        public static String listagem(CaixaDAO cx){
        ArrayList<Caixa> lista = cx.consulta();
        String texto=""; 
        if(lista.isEmpty()) texto = "Não é possível listar!";
        int saldo =0;
        for (int a=0; a< lista.size();a++){
            saldo += lista.get(a).getValor();
            texto += lista.get(a).toString()+" Saldo: R$"+saldo+"\n";
        }
        return texto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgcad;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JRadioButton btnEntrada;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnListar;
    private javax.swing.JRadioButton btnSaida;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel descricao;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel registro;
    private javax.swing.JLabel tipo1;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextArea txtPainel;
    private javax.swing.JTextField txtReg;
    private javax.swing.JTextField txtValor;
    private javax.swing.JLabel valor;
    // End of variables declaration//GEN-END:variables
}
